package claude

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/Vadym903/Intenter/internal/platform"
)

// SkillName is the directory Claude Code takes the `/intenter` command name
// from, and the file inside it that carries the command.
const (
	SkillName     = "intenter"
	SkillFileName = "SKILL.md"
)

// skillMarker identifies a file Intenter wrote. A file at the skill path
// without it belongs to the user, and is backed up before it is replaced.
const skillMarker = "<!-- generated by intenter — do not edit; `intenter setup claude` rewrites it -->"

// SkillAction is one entry of the `/intenter` menu, as the skill file needs it.
//
// The content comes from the CLI, which owns the command surface; this package
// only renders it. That keeps the dependency pointing one way and stops the
// menu and the commands it names from drifting apart.
type SkillAction struct {
	// Name is what the user types after `/intenter`.
	Name string
	// Argument is the placeholder shown in the hint, empty when the action
	// takes none.
	Argument string
	// Summary is the one-line description of what the action does.
	Summary string
	// Command is the intenter command line the action runs, with `%s` where
	// the argument goes.
	Command string
	// Changes marks an action that changes a permission.
	Changes bool
}

// SkillsDir is Claude's top-level personal skills directory.
func SkillsDir(configDir string) string { return filepath.Join(configDir, "skills") }

// SkillDir is the directory this skill occupies.
func SkillDir(configDir string) string { return filepath.Join(SkillsDir(configDir), SkillName) }

// SkillPath is the file Claude Code reads `/intenter` from.
func SkillPath(configDir string) string { return filepath.Join(SkillDir(configDir), SkillFileName) }

// SkillInstall reports what installing the skill did.
type SkillInstall struct {
	// Path is the file that was written.
	Path string
	// BackupPath is where a pre-existing file that Intenter did not write was
	// saved, empty when there was none.
	BackupPath string
	// CreatedSkillsDir is true when the top-level skills directory did not
	// exist. Claude Code only watches directories that existed when the session
	// started, so this is the one case that needs a restart.
	CreatedSkillsDir bool
	// Unchanged is true when the file already held exactly this content.
	Unchanged bool
}

// InstallSkill writes the `/intenter` skill, creating the directories it needs.
//
// A file already at that path which Intenter did not write is copied into the
// backup directory first: the path is ours by convention, not by right.
func InstallSkill(configDir, dataDir string, actions []SkillAction, now time.Time) (SkillInstall, error) {
	install := SkillInstall{Path: SkillPath(configDir)}
	content := RenderSkill(actions)

	if _, err := os.Stat(SkillsDir(configDir)); os.IsNotExist(err) {
		install.CreatedSkillsDir = true
	}

	existing, err := os.ReadFile(install.Path)
	switch {
	case err == nil && string(existing) == content:
		install.Unchanged = true
		return install, nil
	case err == nil && !strings.Contains(string(existing), skillMarker):
		backup, backupErr := backupFile(install.Path, dataDir, "claude-skill", ".md", now)
		if backupErr != nil {
			return install, backupErr
		}
		install.BackupPath = backup
	case err != nil && !os.IsNotExist(err):
		return install, fmt.Errorf("claude: read %s: %w", install.Path, err)
	}

	if err := os.MkdirAll(SkillDir(configDir), platform.DirMode); err != nil {
		return install, fmt.Errorf("claude: create the skill directory: %w", err)
	}
	if err := os.WriteFile(install.Path, []byte(content), 0o600); err != nil {
		return install, fmt.Errorf("claude: write %s: %w", install.Path, err)
	}
	return install, nil
}

// SkillUpToDate reports whether the installed skill is byte-for-byte what this
// build would write. `doctor` uses it to notice a file an older version left.
func SkillUpToDate(configDir string, actions []SkillAction) (bool, error) {
	content, err := os.ReadFile(SkillPath(configDir))
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, fmt.Errorf("claude: read %s: %w", SkillPath(configDir), err)
	}
	return string(content) == RenderSkill(actions), nil
}

// RemoveSkill deletes the skill directory, leaving the rest of the user's
// skills alone. A directory that is not there is not an error: uninstall must
// be re-runnable.
func RemoveSkill(configDir string) (bool, error) {
	dir := SkillDir(configDir)
	if _, err := os.Stat(dir); err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, fmt.Errorf("claude: read %s: %w", dir, err)
	}
	if err := os.RemoveAll(dir); err != nil {
		return false, fmt.Errorf("claude: remove %s: %w", dir, err)
	}
	return true, nil
}

// RenderSkill builds the skill file.
//
// The output depends only on the actions given, in the order given, so two runs
// of the same build produce identical bytes. `intenter update` rewrites this
// file on every upgrade, and a body that reordered itself each time would churn
// a file in the user's own configuration directory for no reason.
func RenderSkill(actions []SkillAction) string {
	var b strings.Builder

	b.WriteString("---\n")
	b.WriteString("name: " + SkillName + "\n")
	b.WriteString("description: Show what Intenter lets this project run without asking, " +
		"and take a permission back.\n")
	b.WriteString("argument-hint: \"" + skillArgumentHint(actions) + "\"\n")
	// Only the user opens a permission menu. Claude must never decide on its own
	// to run something that can remove a permission.
	b.WriteString("disable-model-invocation: true\n")
	// Covers the invoking turn only, and only Intenter's own binary. Setup must
	// never write a rule for `intenter` into the user's permissions.allow: a
	// permission tool that allowlists itself in the file it helps people prune
	// would not deserve the trust.
	b.WriteString("allowed-tools: Bash(intenter *)\n")
	// No `shell:` key on purpose. `shell: bash` fails outright on Windows
	// without Git Bash; left unset, Claude Code uses whichever shell tool the
	// machine has, so every injected command below stays free of shell syntax.
	b.WriteString("---\n\n")

	b.WriteString(skillMarker + "\n\n")

	b.WriteString("## What Intenter allows here\n\n")
	b.WriteString("!`intenter menu`\n\n")

	b.WriteString("## If the section above holds no menu\n\n")
	b.WriteString("Some clients do not run injected commands, and a managed setting can turn\n")
	b.WriteString("them off. If the section above is empty, or says shell execution is\n")
	b.WriteString("disabled, run `intenter menu` with the Bash tool and print its output\n")
	b.WriteString("verbatim. If that fails too, say so and tell the user to run\n")
	b.WriteString("`intenter menu` in a terminal. Never describe from memory what the menu\n")
	b.WriteString("would have said.\n\n")

	b.WriteString("## What to do with the argument\n\n")
	b.WriteString("With no argument, show the menu above and stop. With an argument, run the\n")
	b.WriteString("matching command and print its output verbatim. `$0` is the first\n")
	b.WriteString("argument, `$1` the second.\n\n")
	b.WriteString("| Argument | Command |\n")
	b.WriteString("|---|---|\n")
	for _, act := range actions {
		b.WriteString("| `" + skillArgumentLabel(act) + "` | `" + skillCommand(act) + "` |\n")
	}
	b.WriteString("\nAn argument that names none of these is not a guess to make: show the menu\n")
	b.WriteString("and say the argument was not recognized.\n\n")

	b.WriteString("## Standing rules\n\n")
	b.WriteString("- Print command output verbatim. Never summarise, reorder or re-word a\n")
	b.WriteString("  permission list: the point of this command is that the user sees what\n")
	b.WriteString("  Intenter actually holds.\n")
	b.WriteString("- Never run a command that changes a permission unless the user asked for\n")
	b.WriteString("  it in this turn.\n")
	b.WriteString("- A command that changes something prints what it would change and then\n")
	b.WriteString("  stops, asking to be re-run with `--yes`. That is not an error to work\n")
	b.WriteString("  around: show the user exactly what it printed, ask them to confirm, and\n")
	b.WriteString("  only after they say so, run the same command again with `--yes` added.\n")
	b.WriteString("  Never add `--yes` on the first attempt.\n")
	b.WriteString("- Never invent an identifier. If the user names something the output does\n")
	b.WriteString("  not contain, say so and show the menu again.\n\n")

	b.WriteString("$ARGUMENTS\n")
	return b.String()
}

// skillArgumentHint renders the autocomplete hint from the same list.
func skillArgumentHint(actions []SkillAction) string {
	labels := make([]string, 0, len(actions))
	for _, act := range actions {
		labels = append(labels, skillArgumentLabel(act))
	}
	return strings.Join(labels, " | ")
}

// skillArgumentLabel is how one action is typed.
func skillArgumentLabel(act SkillAction) string {
	if act.Argument == "" {
		return act.Name
	}
	return act.Name + " " + act.Argument
}

// skillCommand fills the action's argument placeholder for the table.
func skillCommand(act SkillAction) string {
	if act.Argument == "" || !strings.Contains(act.Command, "%s") {
		return strings.ReplaceAll(act.Command, "%s", "")
	}
	return fmt.Sprintf(act.Command, act.Argument)
}
