package scope

import (
	"os"
	"path/filepath"
	"sort"
	"testing"

	"github.com/Vadym903/Intenter/internal/action"
)

func TestGeneratedRootsRequireMarkerFiles(t *testing.T) {
	f := newFixture(t)

	generated := []string{
		"dist",                     // next to package.json
		"node_modules",             // next to package.json
		"node_modules/left-pad",    // inside a generated root
		"build",                    // next to package.json (node rule)
		"target",                   // next to pom.xml
		"dist/nested/deep/file.js", // deep inside a generated root
	}
	for _, path := range generated {
		full := filepath.Join(f.workspace, path)
		if !f.ctx.UnderGeneratedRoot(full) {
			t.Errorf("%s must be inside a generated root (§16.4)", path)
		}
	}

	notGenerated := []string{"src", "notes", "notes/build", "package.json", "."}
	for _, path := range notGenerated {
		full := filepath.Clean(filepath.Join(f.workspace, path))
		if f.ctx.UnderGeneratedRoot(full) {
			t.Errorf("%s must not be a generated root: a build/dist folder without a marker file is WORKSPACE", path)
		}
	}
}

func TestGeneratedRootsForGradleAndMaven(t *testing.T) {
	base := t.TempDir()
	workspace := mustEval(t, base)
	mustMkdir(t,
		filepath.Join(workspace, "build"),
		filepath.Join(workspace, "app", "build"),
		filepath.Join(workspace, "buildSrc", "build"),
		filepath.Join(workspace, ".gradle"),
		filepath.Join(workspace, "svc", "target"),
		filepath.Join(workspace, "plain", "build"),
	)
	mustWrite(t,
		filepath.Join(workspace, "settings.gradle.kts"), "",
		filepath.Join(workspace, "app", "build.gradle"), "",
		filepath.Join(workspace, "svc", "pom.xml"), "<project/>",
	)

	ctx := NewContext(hostRules(t), filepath.Dir(workspace), workspace, "", nil)

	generated := []string{"build", "app/build", "buildSrc/build", ".gradle", "svc/target"}
	for _, path := range generated {
		if !ctx.UnderGeneratedRoot(filepath.Join(workspace, path)) {
			t.Errorf("%s must be a generated root (§16.4)", path)
		}
	}
	if ctx.UnderGeneratedRoot(filepath.Join(workspace, "plain", "build")) {
		t.Error("a build directory without a Gradle marker is WORKSPACE, not generated")
	}
}

func TestGeneratedRootsFromConfiguredExtras(t *testing.T) {
	f := newFixture(t)
	mustMkdir(t, filepath.Join(f.workspace, "out"))

	withoutExtra := f.ctx.UnderGeneratedRoot(filepath.Join(f.workspace, "out"))
	if withoutExtra {
		t.Fatal("out/ must not be generated by default")
	}

	ctx := NewContext(f.ctx.Rules, f.home, f.workspace, f.temp, []string{"out"})
	if !ctx.UnderGeneratedRoot(filepath.Join(f.workspace, "out", "bundle.js")) {
		t.Error("scope.generated_dirs_extra must add generated roots (§16.4)")
	}
}

func TestGeneratedRootsIgnorePathsOutsideWorkspace(t *testing.T) {
	f := newFixture(t)

	if f.ctx.UnderGeneratedRoot(filepath.Join(f.home, "dist")) {
		t.Error("generated roots exist only inside the workspace")
	}

	noWorkspace := NewContext(f.ctx.Rules, f.home, "", f.temp, nil)
	if noWorkspace.UnderGeneratedRoot(filepath.Join(f.home, "dist")) {
		t.Error("without a workspace nothing is generated")
	}
}

func TestGeneratedRootsEnumeration(t *testing.T) {
	f := newFixture(t)

	roots := f.ctx.GeneratedRoots()
	names := make([]string, 0, len(roots))
	for _, root := range roots {
		rel, err := filepath.Rel(f.workspace, root)
		if err != nil {
			t.Fatalf("Rel: %v", err)
		}
		names = append(names, filepath.ToSlash(rel))
	}
	sort.Strings(names)

	want := map[string]bool{"build": true, "dist": true, "node_modules": true, "target": true}
	for _, name := range names {
		if !want[name] {
			t.Errorf("unexpected generated root %q", name)
		}
		delete(want, name)
	}
	for name := range want {
		t.Errorf("missing generated root %q", name)
	}
}

func TestGeneratedRootThatEscapesWorkspaceIsNotGenerated(t *testing.T) {
	f := newFixture(t)

	escaping := filepath.Join(f.workspace, "coverage")
	if err := os.Symlink(filepath.Join(f.home, "Documents"), escaping); err != nil {
		t.Skipf("symlink creation not permitted: %v", err)
	}

	for _, root := range f.ctx.GeneratedRoots() {
		if filepath.Base(root) == "coverage" {
			t.Error("a generated root that escapes the workspace must be excluded (§16.4, I-14)")
		}
	}

	target := f.ctx.Normalize(Input{Raw: "coverage", Text: "coverage", Cwd: f.workspace})
	if target.Scope == action.ScopeWorkspaceGenerated {
		t.Errorf("an escaping symlink must never be WORKSPACE_GENERATED, got %s", target.Scope)
	}
	if !target.HasFlag(action.FlagSymlinkEscape) {
		t.Errorf("flags = %v, want symlink_escape", target.Flags)
	}
}
