// Command gendocs writes the CLI reference from the binary's own command tree.
//
// The reference is generated rather than written because a hand-maintained one
// is wrong the first time someone adds a flag and forgets the docs — and a
// reference that is wrong is worse than none, since the reader has no way to
// tell. CI regenerates and diffs, so the two cannot drift.
//
// The markdown is produced here rather than with `cobra/doc` because that
// package drags in a man-page renderer and a YAML library for generators this
// project does not use, and the output format is worth controlling anyway.
//
// Usage:
//
//	go run ./tools/gendocs docs/cli
package main

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"

	"github.com/Vadym903/Intenter/internal/cli"
)

// generatedMarker identifies a page this tool wrote, so a regeneration can
// clean up pages for commands that no longer exist without touching anything
// hand-written in the same directory.
const generatedMarker = "<!-- generated by tools/gendocs — do not edit -->"

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: gendocs <output-dir>")
		os.Exit(2)
	}
	if err := generate(os.Args[1]); err != nil {
		fmt.Fprintln(os.Stderr, "gendocs:", err)
		os.Exit(1)
	}
}

func generate(outputDir string) error {
	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		return err
	}
	if err := removeGenerated(outputDir); err != nil {
		return err
	}

	root, _ := cli.NewRootCommand(io.Discard, io.Discard)
	root.DisableAutoGenTag = true

	commands := allCommands(root)
	for _, command := range commands {
		if err := writePage(outputDir, command); err != nil {
			return err
		}
	}
	return writeIndex(outputDir, root, commands)
}

// removeGenerated deletes the pages a previous run wrote.
func removeGenerated(outputDir string) error {
	entries, err := os.ReadDir(outputDir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}

	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".md") {
			continue
		}
		path := filepath.Join(outputDir, entry.Name())
		content, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if strings.Contains(string(content), generatedMarker) {
			if err := os.Remove(path); err != nil {
				return err
			}
		}
	}
	return nil
}

// dedentExample strips the two-space indent cobra's own help output expects
// on Example lines, so the reference shows the commands flush left instead of
// keeping the first line flush and the rest indented.
func dedentExample(example string) string {
	lines := strings.Split(strings.TrimRight(example, "\n"), "\n")
	for i, line := range lines {
		lines[i] = strings.TrimPrefix(line, "  ")
	}
	return strings.TrimSpace(strings.Join(lines, "\n"))
}

// pageName is the file one command's reference lives in.
func pageName(command *cobra.Command) string {
	return strings.ReplaceAll(command.CommandPath(), " ", "_") + ".md"
}

func writePage(outputDir string, command *cobra.Command) error {
	var page strings.Builder

	page.WriteString(generatedMarker + "\n\n")
	fmt.Fprintf(&page, "# %s\n\n", command.CommandPath())
	fmt.Fprintf(&page, "%s\n\n", command.Short)

	if long := strings.TrimSpace(command.Long); long != "" && long != strings.TrimSpace(command.Short) {
		page.WriteString(long + "\n\n")
	}

	// The language matters to the linter as well as to the renderer: a fence
	// without one is flagged, and thirty generated pages would all be flagged
	// together.
	page.WriteString("## Usage\n\n```text\n" + command.UseLine() + "\n```\n\n")

	if example := dedentExample(command.Example); example != "" {
		page.WriteString("## Examples\n\n```console\n" + example + "\n```\n\n")
	}

	if children := visibleChildren(command); len(children) > 0 {
		page.WriteString("## Subcommands\n\n| Command | What it does |\n|---|---|\n")
		for _, child := range children {
			fmt.Fprintf(&page, "| [`%s`](%s) | %s |\n", child.CommandPath(), pageName(child), child.Short)
		}
		page.WriteString("\n")
	}

	writeFlags(&page, "Options", command.NonInheritedFlags())
	writeFlags(&page, "Options inherited from parent commands", command.InheritedFlags())

	if parent := command.Parent(); parent != nil {
		fmt.Fprintf(&page, "## See also\n\n- [`%s`](%s) — %s\n",
			parent.CommandPath(), pageName(parent), parent.Short)
	}
	page.WriteString("\n[CLI reference](README.md) · [Documentation](../README.md)\n")

	// Sections end with their own blank line, so the footer's leading one can
	// make two in a row — which the documentation linter rejects, on thirty
	// pages at once.
	rendered := strings.ReplaceAll(page.String(), "\n\n\n", "\n\n")
	return os.WriteFile(filepath.Join(outputDir, pageName(command)), []byte(rendered), 0o644)
}

// writeFlags renders one flag set as a table, or nothing when it is empty.
func writeFlags(page *strings.Builder, heading string, flags *pflag.FlagSet) {
	if !flags.HasAvailableFlags() {
		return
	}

	fmt.Fprintf(page, "## %s\n\n| Flag | Default | What it does |\n|---|---|---|\n", heading)
	flags.VisitAll(func(flag *pflag.Flag) {
		if flag.Hidden {
			return
		}
		name := "`--" + flag.Name + "`"
		if flag.Shorthand != "" {
			name = "`-" + flag.Shorthand + "`, " + name
		}
		if flag.Value.Type() != "bool" {
			name += " `<" + flag.Value.Type() + ">`"
		}

		defaultValue := "—"
		if flag.DefValue != "" && flag.DefValue != "false" && flag.DefValue != "[]" {
			defaultValue = "`" + flag.DefValue + "`"
		}
		fmt.Fprintf(page, "| %s | %s | %s |\n", name, defaultValue, flag.Usage)
	})
	page.WriteString("\n")
}

// writeIndex lists every command on one page, which is what a reader arriving
// from the README wants first.
func writeIndex(outputDir string, root *cobra.Command, commands []*cobra.Command) error {
	var page strings.Builder

	page.WriteString(generatedMarker + "\n\n")
	page.WriteString("# Intenter CLI reference\n\n")
	page.WriteString(strings.TrimSpace(root.Long) + "\n\n")
	page.WriteString("Every list and show command accepts `--json` for scripting.\n")
	page.WriteString("Exit codes: `0` success, `1` error, `2` the daemon is unreachable.\n\n")
	page.WriteString("| Command | What it does |\n|---|---|\n")

	for _, command := range commands {
		if command == root {
			continue
		}
		fmt.Fprintf(&page, "| [`%s`](%s) | %s |\n", command.CommandPath(), pageName(command), command.Short)
	}

	page.WriteString("\n[Documentation](../README.md)\n")
	return os.WriteFile(filepath.Join(outputDir, "README.md"), []byte(page.String()), 0o644)
}

// allCommands walks the command tree depth first, skipping hidden and
// cobra-generated commands.
func allCommands(root *cobra.Command) []*cobra.Command {
	out := []*cobra.Command{root}
	for _, child := range visibleChildren(root) {
		out = append(out, allCommands(child)...)
	}
	return out
}

func visibleChildren(command *cobra.Command) []*cobra.Command {
	var out []*cobra.Command
	for _, child := range command.Commands() {
		if child.Hidden || child.Name() == "help" || child.Name() == "completion" {
			continue
		}
		out = append(out, child)
	}
	return out
}
